### ISSUE TITLE
Translation tool ?

### ISSUE THREAD

**Issue by hanschan6648** [isyuricunha/sands-of-salzaar-game-translation#1]
Hello, what tool do you use to translate the game? I also want to translate the game into my language.
Thank bro.

**Comment by isyuricunha** [comment]
Hey man,

So, the only tools I used were Excel and DeepL. To check for errors, I had some friends who played and they would inform me what was wrong.

**Comment by hanschan6648** [comment]
It seems you misunderstood my meaning. I want to ask for a tool so you can export text and import text from a .byte file. I searched on the internet but couldn't find any such tool.
Sorry for bothering you

**Comment by isyuricunha** [comment]
> It seems you misunderstood my meaning. I want to ask for a tool so you can export text and import text from a .byte file. I searched on the internet but couldn't find any such tool. Sorry for bothering you

Now it is understandable.
Dude, to generate these files, you need to build inside the game. In other words, you need to have the game, open the mod folder there, and then build it.
